import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [query, getQuery] = useState();
  const router = useRouter();
  const handleOnChange = (e) => getQuery(e.target.value);
  const handleOnSubmit = (e) => {
    e.preventDefault();
    router.push(`/news/${query}`);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>News Feed</h1>

        <form onSubmit={handleOnSubmit}>
          <input type="text" onChange={handleOnChange} />
        </form>

        <div className={styles.grid}>
          <Link href="/news/">
            <h2>Top Stories &rarr;</h2>
            <p>Read articles currently on the homepage</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
}
